[package]
name = "trusttunnel_agent"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "trusttunnel_sidecar_agent"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
libc = "0.2"
log = "0.4"
env_logger = "0.11"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
tokio = { version = "1.42", features = ["macros", "rt-multi-thread", "time", "net", "signal"] }
toml = { version = "0.8", default-features = false, features = ["display"] }

[dev-dependencies]
httpmock = "0.7"
