apiVersion: v1
kind: Service
metadata:
  name: {{ default .Chart.Name .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/name: trusttunnel
spec:
  selector:
    app.kubernetes.io/name: trusttunnel
    app.kubernetes.io/part-of: trusttunnel-classic
  type: {{ .Values.endpoint.service.type }}
  ports:
    - name: https-tcp
      port: {{ .Values.endpoint.service.tcpPort }}
      protocol: TCP
      targetPort: {{ .Values.endpoint.service.targetPort }}
    - name: https-udp
      port: {{ .Values.endpoint.service.udpPort }}
      protocol: UDP
      targetPort: {{ .Values.endpoint.service.targetPort }}
