{{- if and .Values.sidecarEnabled .Values.sidecar.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sidecar.serviceAccountName | default (default .Chart.Name .Values.fullnameOverride) }}
  labels:
    app.kubernetes.io/name: trusttunnel
    app.kubernetes.io/part-of: trusttunnel-classic
{{- end }}
