name: Run tests

on:
  push:
    branches:
      - master
      - 'stable-*'
      - 'dev-*'
  pull_request:
  workflow_dispatch:

jobs:
  linux-build:
    name: Linux build
    if: github.repository == 'AdGuardSoftwareLimited/trusttunnel-endpoint'
    runs-on:
      - ephemeral
      - ephemeral-linux
      - ${{ vars.BUILD_IMAGE_VERSION_CORELIBS_BUILDER }}
      - ephemeral-limit-memory-8192
      - ephemeral-limit-cpu-6
      - ephemeral-job-key-${{ github.run_id }}-${{ github.job }}-${{ strategy.job-index || 0 }}
    container:
      image: adguard/core-libs:2.10
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run tests
        run: cargo test --workspace
      - name: Build binaries
        run: cargo build --bins
      - name: Lint Rust
        run: |
          rustup component add rustfmt clippy
          make lint-rust

  mac-build:
    name: Mac build
    if: github.repository == 'AdGuardSoftwareLimited/trusttunnel-endpoint'
    runs-on:
      - ephemeral
      - ephemeral-mac
      - ${{ vars.BUILD_IMAGE_VERSION_MACOS }}
      - ephemeral-job-key-${{ github.run_id }}-${{ github.job }}-${{ strategy.job-index || 0 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run tests
        run: cargo test --workspace
      - name: Build binaries
        run: cargo build --bins
